### ISSUE TITLE
No serializable introspection present for type Inet4Address with Serde

### ISSUE THREAD

**Issue by message** [micronaut-projects/micronaut-discovery-client#385] opened 2022-12-07 22:08 UTC
### Expected Behavior

Not failing

### Before `@SerdeImport(Inet4Address.class)`

Java:
```
2022-12-07 22:44:12,338 [default-nioEventLoopGroup-1-2] WARN  io.netty.channel.DefaultChannelPipeline:1152 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException: null
2022-12-07 22:44:18,369 [default-nioEventLoopGroup-1-3] WARN  io.netty.channel.DefaultChannelPipeline:1152 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException: null
2022-12-07 22:44:27,373 [default-nioEventLoopGroup-1-4] WARN  io.netty.channel.DefaultChannelPipeline:1152 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException: null
2022-12-07 22:44:29,368 [default-nioEventLoopGroup-1-5] ERROR io.micronaut.discovery.client.registration.DiscoveryServiceAutoRegistration$1:83 - Error occurred during service registration with Consul: Error encoding object [io.micronaut.discovery.consul.client.v1.NewServiceEntry@d3092a09] to JSON: No serializable introspection present for type Inet4Address. Consider adding Serdeable. Serializable annotate to type Inet4Address. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(Inet4Address.class) to enable serialization of this type.
io.micronaut.http.codec.CodecException: Error encoding object [io.micronaut.discovery.consul.client.v1.NewServiceEntry@d3092a09] to JSON: No serializable introspection present for type Inet4Address. Consider adding Serdeable. Serializable annotate to type Inet4Address. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(Inet4Address.class) to enable serialization of this type.
	at io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:212)
	at io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:258)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$buildNettyRequest$41(DefaultHttpClient.java:1340)
	at java.base/java.util.Optional.map(Optional.java:260)
```

Consul:
```
2022-12-07T21:45:28.719Z [DEBUG] agent: Node info in sync
2022-12-07T21:45:44.485Z [ERROR] agent.http: Request error: method=PUT url="/v1/agent/service/deregister/users%3A773d43e0d4" from=10.0.2.100:54606 error="Unknown service ID \"users:773d43e0d4\". Ensure that the service ID is passed, not the service name."
2022-12-07T21:45:44.485Z [DEBUG] agent.http: Request finished: method=PUT url="/v1/agent/service/deregister/users%3A773d43e0d4" from=10.0.2.100:54606 latency="38.971µs"

```

### After `@SerdeImport(Inet4Address.class)`

Java:
```
2022-12-07 22:46:51,905 [default-nioEventLoopGroup-1-5] ERROR io.micronaut.discovery.client.registration.DiscoveryServiceAutoRegistration$1:83 - Error occurred during service registration with Consul: Request decode failed: json: cannot unmarshal object into Go struct field .Address of type string
io.micronaut.http.client.exceptions.HttpClientResponseException: Request decode failed: json: cannot unmarshal object into Go struct field .Address of type string
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeErrorFromRequestBody(DefaultHttpClient.java:2253)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:2215)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:2138)
	at io.micronaut.http.client.netty.DefaultHttpClient$BaseHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2113)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2174)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2138)
	at io.micronaut.http.client.netty.SimpleChannelInboundHandlerInstrumented.channelRead0(SimpleChannelInboundHandlerInstrumented.java:49)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:215)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:180)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
2022-12-07 22:46:51,915 [default-nioEventLoopGroup-1-5] INFO  io.micronaut.discovery.client.registration.DiscoveryServiceAutoRegistration:136 - De-registered service [users] with Consul
```

Consul:
```
2022-12-07T21:46:12.221Z [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="9fb5babb1567.dc1 (Addr: tcp/127.0.0.1:8300) (DC: dc1)"
2022-12-07T21:46:24.874Z [ERROR] agent.http: Request error: method=PUT url=/v1/agent/service/register from=10.0.2.100:43834 error="Request decode failed: json: cannot unmarshal object into Go struct field .Address of type string"
2022-12-07T21:46:24.874Z [DEBUG] agent.http: Request finished: method=PUT url=/v1/agent/service/register from=10.0.2.100:43834 latency="118.011µs"
2022-12-07T21:46:30.888Z [ERROR] agent.http: Request error: method=PUT url=/v1/agent/service/register from=10.0.2.100:52772 error="Request decode failed: json: cannot unmarshal object into Go struct field .Address of type string"
2022-12-07T21:46:30.888Z [DEBUG] agent.http: Request finished: method=PUT url=/v1/agent/service/register from=10.0.2.100:52772 latency="136.531µs"
2022-12-07T21:46:39.893Z [ERROR] agent.http: Request error: method=PUT url=/v1/agent/service/register from=10.0.2.100:39200 error="Request decode failed: json: cannot unmarshal object into Go struct field .Address of type string"
2022-12-07T21:46:39.893Z [DEBUG] agent.http: Request finished: method=PUT url=/v1/agent/service/register from=10.0.2.100:39200 latency="140.581µs"
2022-12-07T21:46:51.900Z [ERROR] agent.http: Request error: method=PUT url=/v1/agent/service/register from=10.0.2.100:53236 error="Request decode failed: json: cannot unmarshal object into Go struct field .Address of type string"
2022-12-07T21:46:51.900Z [DEBUG] agent.http: Request finished: method=PUT url=/v1/agent/service/register from=10.0.2.100:53236 latency="108.231µs"
2022-12-07T21:46:51.914Z [ERROR] agent.http: Request error: method=PUT url="/v1/agent/service/deregister/users%3A79d3a09b97" from=10.0.2.100:53244 error="Unknown service ID \"users:79d3a09b97\". Ensure that the service ID is passed, not the service name."
2022-12-07T21:46:51.915Z [DEBUG] agent.http: Request finished: method=PUT url="/v1/agent/service/deregister/users%3A79d3a09b97" from=10.0.2.100:53244 latency="48.32µs"
```

### Steps To Reproduce

Run [discovery-fail.zip](https://github.com/micronaut-projects/micronaut-discovery-client/files/10180362/discovery-fail.zip)

### Environment Information

Consul: 1.14.2 (Docker)

### Version

3.7.4

**Comment by message** [comment] 2022-12-08 15:04
[CONSUL AND THE MICRONAUT FRAMEWORK - MICROSERVICES SERVICE DISCOVERY](https://guides.micronaut.io/latest/micronaut-microservices-services-discover-consul-gradle-java.html) guide also fails.

**Comment by alvarosanchez** [comment] 2022-12-13 10:47
I've seen this issue too.

We have the intention to replace Jackson with Micronaut Serialization in this module for Micronaut 4, however, we are not there yet. Once #379 is done, I will give it a try.

**Comment by stmty9** [comment] 2023-01-27 22:48
Any update on this? I am having the same issue:
micronaut: 3.7.0
discovery-client: 3.1.0
consul (docker): 1.14.3

**Comment by stmty9** [comment] 2023-01-28 05:04
The issue is with the serialization. There appears to not be a suitable Serde for InetAddress (I am using micronaut serialization).

I made my own Serde which seems to work (no need for `@SerdeImport` anymore. I have only tested this using `localhost`, so it may need some more testing.

```
@Singleton
public class InetAddressSerde implements Serde<InetAddress> {
    @Nullable
    @Override
    public InetAddress deserialize(Decoder decoder, DecoderContext context, Argument<? super InetAddress> type) throws IOException {
        return InetAddress.getByName(decoder.decodeString());
    }

    @Override
    public void serialize(Encoder encoder, EncoderContext context, Argument<? extends InetAddress> type, InetAddress value) throws IOException {
        encoder.encodeString(value.getHostAddress());
    }
}
```

**Why?**
It looks like the registration is attempting to utilize [this service](https://developer.hashicorp.com/consul/api-docs/agent/service#register-service)
The serialized registration FROM micronaut using `@SerdeImport` is:
```
{
  "checks": [
    {
      "TTL": "25s",
      "status": "passing"
    }
  ],
  "ID": "my-svc:55e23743cb",
  "address": {
    "multicastAddress": false,
    "anyLocalAddress": false,
    "loopbackAddress": true,
    "linkLocalAddress": false,
    "siteLocalAddress": false,
    "MCGlobal": false,
    "MCNodeLocal": false,
    "MCLinkLocal": false,
    "MCSiteLocal": false,
    "MCOrgLocal": false,
    "address": [127, 0, 0, 1],
    "hostAddress": "127.0.0.1",
    "hostName": "localhost",
    "canonicalHostName": "localhost"
  },
  "port": 8081,
  "name": "my-svc"
}
```
[This is a sample payload.](https://developer.hashicorp.com/consul/api-docs/agent/service#register-service)

It might be as easy as using `InetAddress.getHostAddress()`

**Comment by averri** [comment] 2023-02-15 18:54
> The issue is with the serialization. There appears to not be a suitable Serde for InetAddress (I am using micronaut serialization).
> 
> I made my own Serde which seems to work (no need for `@SerdeImport` anymore. I have only tested this using `localhost`, so it may need some more testing.
> 
> ```
> @Singleton
> public class InetAddressSerde implements Serde<InetAddress> {
>     @Nullable
>     @Override
>     public InetAddress deserialize(Decoder decoder, DecoderContext context, Argument<? super InetAddress> type) throws IOException {
>         return InetAddress.getByName(decoder.decodeString());
>     }
> 
>     @Override
>     public void serialize(Encoder encoder, EncoderContext context, Argument<? extends InetAddress> type, InetAddress value) throws IOException {
>         encoder.encodeString(value.getHostAddress());
>     }
> }
> ```
> 
> **Why?** It looks like the registration is attempting to utilize [this service](https://developer.hashicorp.com/consul/api-docs/agent/service#register-service) The serialized registration FROM micronaut using `@SerdeImport` is:
> 
> ```
> {
>   "checks": [
>     {
>       "TTL": "25s",
>       "status": "passing"
>     }
>   ],
>   "ID": "my-svc:55e23743cb",
>   "address": {
>     "multicastAddress": false,
>     "anyLocalAddress": false,
>     "loopbackAddress": true,
>     "linkLocalAddress": false,
>     "siteLocalAddress": false,
>     "MCGlobal": false,
>     "MCNodeLocal": false,
>     "MCLinkLocal": false,
>     "MCSiteLocal": false,
>     "MCOrgLocal": false,
>     "address": [127, 0, 0, 1],
>     "hostAddress": "127.0.0.1",
>     "hostName": "localhost",
>     "canonicalHostName": "localhost"
>   },
>   "port": 8081,
>   "name": "my-svc"
> }
> ```
> 
> [This is a sample payload.](https://developer.hashicorp.com/consul/api-docs/agent/service#register-service) from their docs

@stmty9, thank you so much for sharing the custom Serde code.

**Comment by sdelamo** [comment] 2023-10-10 08:26
closed via https://github.com/micronaut-projects/micronaut-serialization/issues/593 and https://github.com/micronaut-projects/micronaut-discovery-client/pull/523

**Closed by sdelamo** 2023-10-10 08:26 UTC
Labels: status: validated, type: bug
